### ISSUE TITLE
Issues when mentioning users

### ISSUE THREAD

**Issue by Daksh777** [nminaya/grammar-nazi-bot#2] opened 2020-09-29 16:39 UTC
![image](https://user-images.githubusercontent.com/43648146/94587610-77087d00-02a0-11eb-92ef-5f71d8303355.png)

**Comment by nminaya** [comment] 2020-09-29 19:28
The issue is now fixed, please try again and let me know @Daksh777

**Closed by nminaya** 2020-09-29 19:28 UTC
Labels: bug

**Comment by Daksh777** [comment] 2020-09-30 04:08
It worked, thank you!
